# Generated by Django 5.0.4 on 2024-04-26 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0005_meetup_date_meetup_organizer_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetup',
            old_name='Participant',
            new_name='participants',
        ),
    ]
